spring.config.activate.on-profile=local

#DB IDCONTROL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/idcontrol}
spring.datasource.username=${DB_USERNAME:des}
spring.datasource.password=${DB_PASSWORD:12345}

#Driver de la base de datos para MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#Opcional: Dialecto de Hibernate para MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


#---------------------------------------------------------------------------------------------------------------------------------------
#Explicaci\u00f3n del atributo "ddl-auto"
#ddl-auto: none, validate, update, create, create-drop

#none: No hace ningun cambio en la base de datos - Producci\u00f3n cunado administras la BD manualmente o con migraciones.
#validate: Verifica que las tablas coincidan con las entidades. Si algo no coincide, la aplicaci\u00f3n falla al iniciar - Producci\u00f3n
#update: Crea tablas y agrega columnas nuevas si hacen falta. No elimina tablas ni columnas existente - Desarrollo
#create: Elimina la base de datos existente y la vuelve a crear cada vez que inicia la aplicaci\u00f3n - Pruiebas o proyectos temporales
#create-drop: Igual que create, pero adem\u00e1s elimina las tablas cuando la aplicaci\u00f3n se detiene. - Test automatizados
spring.jpa.hibernate.ddl-auto=update
#-----------------------------------------------------------------------------------------------------------------------------------------


# Opcional: Configuraciones adicionales de JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

#Limitar la documentaci\u00c3\u00b3n de APIs, para el package de controladores
springdoc.api-docs.path=/api-docs
#Limitar la documentacion de APIs, para el package 'controller'
springdoc.packages-to-scan=com.id.control.controller

#Swagger 
springdoc.swagger-ui.theme=dark

#Logs Level
logging.level.root=DEBUG
logging.level.logiin-passkey=DEBUG
logging.level.org.springframework=INFO
logging.level.org.springframework.security=TRACE
logging.level.com.example=DEBUG

#SQL detallado
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Define zona horaria
spring.jackson.time-zone=America/Mexico_City

# Define el Header de CORS para permitir solicitudes desde el frontend
spring.web.cors.allowed-origins=http://localhost:4200
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*

#Define el Header para autorizar el uso de endpoints protegidos
# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/master

#Propiedades de JWT
security.api.header=Authorization
security.api.prefix=Bearer
security.api.secret=${API_SECRET:1B1DDAA8AE343D53A106C91BE832B1FDB8A94505D9CD0E479B2D9AAA0CC044BA}



#======================================
# Variables de entorno de desarrollo local
#======================================
webauthn.rpId=localhost
webauthn.rpName=IDCONTROL-LOCAL
webauthn.origin=http://localhost:8080