spring.application.name=idcontrol
#Perfil activo por defecto
spring.profiles.active=local
#Disable Open Session In View (best practice)
spring.jpa.open-in-view=false
#Colocar puerto por defecto o en variables de entorno como PORT:8003
server.port=${PORT:8080}
#Logs 
logging.level.root=INFO